apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboards
  namespace: monitoring
data:
  k8s-overview.json: |
    { "annotations": { }, "panels": [], "title": "K8s Overview", "version": 1 }
