apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespaces.yaml
  - ../ingress-nginx
  - ../cert-manager
  - ../argo-rollouts
  - ../monitoring
  - ../opentelemetry
