apiVersion: v1
kind: Namespace
metadata: { name: ingress-nginx }
---
apiVersion: v1
kind: Namespace
metadata: { name: argo-rollouts }
---
apiVersion: v1
kind: Namespace
metadata: { name: cert-manager }
---
apiVersion: v1
kind: Namespace
metadata: { name: monitoring }
