apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: hello
resources:
  - namespace.yaml
  - service.yaml
  - ingress.yaml
  # Choose ONE of the following: rolling OR canary OR blue/green
  # - deployment-rolling.yaml
  # - rollout-canary.yaml
  # - rollout-bluegreen.yaml
