name: Validate
on: [push, pull_request]
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with: { terraform_version: 1.6.6 }
      - name: Terraform fmt check
        run: terraform -chdir=environments/aws/us-east-1/cluster/terraform fmt -check
      - name: YAML lint
        run: pipx install yamllint && yamllint .
